// Converts scripts/seed/data.json (output of the seed-research workflow) into
// supabase/seed/02_spots.sql. Computes slug, price_band, geom, and resolves
// nearest metro via the DB function at insert time.
//
//   node scripts/seed/build-seed.mjs
//   supabase db reset            # re-applies reference + spots
//
// data.json shape: { spots: [...], events: [...] }

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const dataPath = join(here, "data.json");
const outPath = join(root, "supabase", "seed", "02_spots.sql");

const VALID_NEIGHBORHOODS = new Set([
  "koramangala", "indiranagar", "hsr-layout", "btm-layout", "jayanagar",
  "jp-nagar", "whitefield", "marathahalli", "electronic-city", "hebbal", "bellandur",
]);
const VALID_UNITS = new Set([
  "per_plate", "per_person", "per_month", "per_visit", "per_day", "free",
]);

const sq = (s) => (s == null ? null : String(s).replace(/'/g, "''"));
const lit = (s) => (s == null || s === "" ? "null" : `'${sq(s)}'`);
const num = (n) => (n == null || Number.isNaN(Number(n)) ? "null" : Number(n));

function slugify(name, area) {
  const base = `${name} ${area || ""}`
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 70);
  return base || "spot";
}

function priceBand(min, max, unit) {
  if (unit === "free") return "free";
  const v = max ?? min;
  if (v == null) return "any";
  if (v === 0) return "free";
  if (unit === "per_month") return "any"; // rent doesn't fit the food bands
  if (v <= 100) return "under_100";
  if (v <= 300) return "under_300";
  if (v <= 1000) return "under_1000";
  return "any";
}

const data = JSON.parse(readFileSync(dataPath, "utf8"));
const spots = data.spots || [];
const events = data.events || [];

const usedSlugs = new Set();
const lines = [];
lines.push("-- Generated by scripts/seed/build-seed.mjs — do not edit by hand.\n");

let kept = 0;
for (const s of spots) {
  if (!s.name || s.lat == null || s.lng == null) continue;
  if (Math.abs(s.lat - 12.97) > 0.6 || Math.abs(s.lng - 77.59) > 0.6) continue; // sanity: inside BLR
  let slug = slugify(s.name, s.area);
  while (usedSlugs.has(slug)) slug = `${slug}-${usedSlugs.size}`;
  usedSlugs.add(slug);

  const nb = VALID_NEIGHBORHOODS.has(s.neighborhood) ? s.neighborhood : null;
  const unit = VALID_UNITS.has(s.price_unit) ? s.price_unit : "per_person";
  const band = priceBand(s.price_min, s.price_max, unit);
  const geom = `ST_MakePoint(${num(s.lng)}, ${num(s.lat)})::geography`;
  const nbExpr = nb ? `(select id from neighborhoods where slug='${nb}')` : "null";

  lines.push(
    `insert into spots (slug, name, category_id, neighborhood_id, geom, address, ` +
      `price_min, price_max, price_unit, price_band, description, why_worth_it, ` +
      `external_url, instagram, nearest_metro_id, status) values (` +
      `${lit(slug)}, ${lit(s.name)}, ` +
      `(select id from categories where slug=${lit(s.category)}), ` +
      `${nbExpr}, ${geom}, ${lit(s.address)}, ` +
      `${num(s.price_min)}, ${num(s.price_max)}, '${unit}', '${band}', ` +
      `${lit(s.description)}, ${lit(s.why_worth_it)}, ` +
      `${lit(s.external_url)}, ${lit(s.instagram)}, ` +
      `nearest_metro(${geom}), 'approved')` +
      ` on conflict (slug) do nothing;`,
  );

  // tags
  for (const t of (s.tags || []).slice(0, 5)) {
    const tslug = slugify(t, "");
    if (!tslug) continue;
    lines.push(
      `insert into tags (slug, label) values (${lit(tslug)}, ${lit(t)}) on conflict (slug) do nothing;`,
    );
    lines.push(
      `insert into spot_tags (spot_id, tag_id) values (` +
        `(select id from spots where slug=${lit(slug)}), ` +
        `(select id from tags where slug=${lit(tslug)})) on conflict do nothing;`,
    );
  }
  kept++;
}

lines.push("\n-- events --");
let evKept = 0;
for (const e of events) {
  if (!e.title) continue;
  const nb = VALID_NEIGHBORHOODS.has(e.neighborhood) ? e.neighborhood : null;
  const nbExpr = nb ? `(select id from neighborhoods where slug='${nb}')` : "null";
  // schedule a representative upcoming date so the events page has content
  const days = (evKept % 21) + 1;
  lines.push(
    `insert into events (title, venue, neighborhood_id, starts_at, price, description, link, status) values (` +
      `${lit(e.title)}, ${lit(e.venue)}, ${nbExpr}, ` +
      `now() + interval '${days} days', ${num(e.price)}, ` +
      `${lit([e.cadence, e.description].filter(Boolean).join(" — "))}, ${lit(e.link)}, 'approved');`,
  );
  evKept++;
}

writeFileSync(outPath, lines.join("\n") + "\n");
console.log(`Wrote ${outPath}: ${kept} spots, ${evKept} events.`);
